---
abstract: 'Hash Sorting.'
author:
  - 'John Karr <brainbuz@brainbuz.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sort-Hash
requires:
  perl: 5.008
version: 1.01
